[versions]
springboot-dependency-management = "1.1.7"
springboot-framework = "4.1.1"
uuid-creator = "6.1.1"
sentry = "6.22.0"
reckon = "2.0.0"
catalogUpdater = "1.1.1"
jetbrains-annotations = "26.1.0"
anisekai-scheduler = "1.5.0"
anisekai-wireless = "4.0.0-rc.3"
anisekai-ffmpeg = "1.1.0"
springdoc = "3.1.1"
jackson = "2.17.1"
junit-bom = "6.2.0"

[libraries]
api-anisekai-ffmpeg = { module = "fr.anisekai:ffmpeg4j", version.ref = "anisekai-ffmpeg" }
api-anisekai-scheduler = { module = "fr.anisekai:scheduler", version.ref = "anisekai-scheduler" }
api-anisekai-wireless = { module = "fr.anisekai:wireless", version.ref = "anisekai-wireless" }
dev-annotations-jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
spring-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient" }
spring-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-config-processor = { module = "org.springframework.boot:spring-boot-configuration-processor" }
spring-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
testing-spring-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
testing-spring-restclient = { module = "org.springframework.boot:spring-boot-starter-restclient-test" }
testing-junit = { module = "org.junit.platform:junit-platform-launcher" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }

[plugins]
catalogUpdater = { id = "nl.littlerobots.version-catalog-update", version.ref = "catalogUpdater" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckon" }
sentry = { id = "io.sentry.jvm.gradle", version.ref = "sentry" }
spring-framework = { id = "org.springframework.boot", version.ref = "springboot-framework" }
spring-dependencyManagement = { id = "io.spring.dependency-management", version.ref = "springboot-dependency-management" }

[bundles]
anisekai = [
    "api-anisekai-ffmpeg",
    "api-anisekai-scheduler",
    "api-anisekai-wireless"
]

springboot = [
    "spring-restclient",
    "spring-webmvc",
    "spring-actuator",
    "spring-config-processor",
    "spring-validation"
]

springboot-test = [
    "testing-spring-restclient",
    "testing-spring-webmvc"
]